"""Interview-guide models — the personalized human-interview guide for one
shortlisted candidate (CLAUDE.md §§3, 6, 12, 19, 20; Phase 4 Step 7).

The guide is generated by AI from the candidate's full evaluation record and is
read by a **human interviewer** before the interview. This MVP has NO live AI
interviewer (CLAUDE.md §6) — the AI produces the guide, a person runs the
interview.

WHY ``rubric_version_id`` IS A FROZEN COPY OF THE SHORTLIST'S CAPTURED VERSION
--------------------------------------------------------------------------
``InterviewGuide.rubric_version_id`` is populated by reading
``candidate_shortlist_entries.rubric_version_id`` — the rubric version the
shortlist decision was made against, captured at *shortlist* time. It is **never**
set from ``rubric_service.get_approved_rubric(job_id)`` and never re-derived from
the job's current approved rubric.

Reason: a job's approved rubric can be superseded after a candidate is
shortlisted. The interview must probe the criteria the candidate was actually
*evaluated and ranked against* — otherwise the interviewer would be validating a
yardstick nobody scored this candidate on. This holds **even when that captured
version's status is now ``SUPERSEDED``**: a SUPERSEDED ``RubricVersion`` and its
``RubricCriterion`` rows remain permanently readable (nothing archives or deletes
them), so ``list_criteria(db, rubric_version_id=<captured id>)`` still returns the
exact criteria set the guide must be grounded in. Regeneration re-reads the
*same* shortlist entry's captured id, not a fresh one.

WHY REPLACE-IN-PLACE, NOT APPEND-ONLY
-----------------------------------
One ``interview_guides`` row per application (``UNIQUE(application_id)``).
Regeneration deletes the old guide + its questions and inserts a fresh set —
the same "current state in the table, history in the audit log" philosophy as
``screening_evaluations`` and ``candidate_rankings``. Every generation and
regeneration emits one ``INTERVIEW_GUIDE_GENERATED`` audit event; that trail,
not accumulated rows, is the history.

Design decisions
----------------
ID type — **UUID v4**, Python-side ``default=uuid.uuid4`` (project precedent).

FKs — ``job_id`` / ``application_id`` / ``shortlist_entry_id`` /
``rubric_version_id`` and ``interview_questions.interview_guide_id`` /
``rubric_criterion_id`` are all **``ON DELETE RESTRICT``** — the same
"independent business/audit record, never a silent cascade" convention as every
other AI-output table.

``InterviewQuestion.rubric_criterion_id`` is nullable — BEHAVIORAL / PROBING
questions need not map to a single criterion, the same pattern as
``screening_questions.rubric_criterion_id``.

``generated_reason`` / ``evaluates`` / ``question_text`` are free text — HR /
interviewer facing, **never** placed in audit metadata (they can quote résumé /
screening content).

No ``updated_at`` — a guide row is write-once within its generation (replace =
delete + insert, matching ``screening_evaluations``).
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.database import Base


class InterviewQuestionCategory:
    """The five interview-question categories (validated string column).

    Deliberately NO "TECHNICAL" value — this codebase has no reliable
    technical / non-technical classification axis (the same reason Step 4/5's
    score buckets are "Requirements", not "Technical"). The five values map to
    CLAUDE.md §6's guide contents:

    * ``REQUIREMENTS``      — validates a mandatory / preferred / other rubric
      requirement.
    * ``EXPERIENCE``        — validates an experience-type rubric criterion.
    * ``BEHAVIORAL``        — assesses an approved behavioral competency.
    * ``RESUME_VALIDATION`` — checks a specific résumé claim / project /
      technology / date.
    * ``PROBING``           — a follow-up that explores a gap, unknown, or
      ambiguous screening answer.
    """

    REQUIREMENTS = "REQUIREMENTS"
    EXPERIENCE = "EXPERIENCE"
    BEHAVIORAL = "BEHAVIORAL"
    RESUME_VALIDATION = "RESUME_VALIDATION"
    PROBING = "PROBING"

    ALL: frozenset[str] = frozenset(
        {REQUIREMENTS, EXPERIENCE, BEHAVIORAL, RESUME_VALIDATION, PROBING}
    )

    #: Stable display order for the HR guide view.
    ORDER: tuple[str, ...] = (
        REQUIREMENTS,
        EXPERIENCE,
        BEHAVIORAL,
        RESUME_VALIDATION,
        PROBING,
    )

    @classmethod
    def is_valid(cls, value: str) -> bool:
        return value in cls.ALL


class InterviewGuide(Base):
    """One personalized human-interview guide for one shortlisted candidate."""

    __tablename__ = "interview_guides"

    __table_args__ = (
        UniqueConstraint(
            "application_id", name="uq_interview_guides_application"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    application_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("applications.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Traceability to the shortlist decision that grounded this guide.
    shortlist_entry_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("candidate_shortlist_entries.id", ondelete="RESTRICT"),
        nullable=False,
    )

    # FROZEN COPY of shortlist_entry.rubric_version_id at generation time.
    # NEVER set from get_approved_rubric(job_id). See the module docstring.
    rubric_version_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("rubric_versions.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    ai_model: Mapped[str] = mapped_column(String(100), nullable=False)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:  # pragma: no cover - debug helper only
        return (
            f"<InterviewGuide id={self.id!r} application={self.application_id!r} "
            f"rubric_version={self.rubric_version_id!r}>"
        )


class InterviewQuestion(Base):
    """One AI-generated question within an interview guide."""

    __tablename__ = "interview_questions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    interview_guide_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_guides.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Validated against InterviewQuestionCategory at the service layer.
    category: Mapped[str] = mapped_column(String(50), nullable=False)

    # NULL for a BEHAVIORAL / PROBING question that maps to no single criterion.
    rubric_criterion_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("rubric_criteria.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )

    sequence_index: Mapped[int] = mapped_column(Integer, nullable=False)

    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    # What the interviewer should be checking with this question.
    evaluates: Mapped[str] = mapped_column(Text, nullable=False)
    # Why the AI generated this question (CLAUDE.md §6). HR/interviewer facing;
    # NEVER in audit metadata (may quote résumé / screening content).
    generated_reason: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:  # pragma: no cover - debug helper only
        # No question_text / evaluates / generated_reason (free text).
        return (
            f"<InterviewQuestion id={self.id!r} "
            f"guide={self.interview_guide_id!r} category={self.category!r} "
            f"seq={self.sequence_index}>"
        )
